# Copyright (c) 2023, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

services:
  backend-service:
    environment:
      OTEL_SERVICE_NAME: backend-service
      OTEL_TRACES_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_METRIC_EXPORT_INTERVAL: 5000
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:${OTEL_COLLECTOR_OTLP_PORT}"
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      # Micrometer OTLP registry configuration
      MANAGEMENT_METRICS_EXPORT_OTLP_URL: "http://otel-collector:4318/v1/metrics"
      MANAGEMENT_METRICS_EXPORT_OTLP_ENABLED: "true"
      MANAGEMENT_METRICS_EXPORT_OTLP_STEP: "10s"
