package com.digitalasset.quickstart.dto;

public enum ErrorCode {
    VALIDATION,
    NOT_FOUND,
    FORBIDDEN,
    LEDGER_AUTH,
    PRECONDITION_FAILED,
    MISSING_INBOUND_TIS_FOR_POOL_INSTRUMENT,
    LEGACY_LP_POOL_NOT_FOUND,
    CONFLICT,
    LEDGER_REJECTED,
    TIMEOUT,
    INTERNAL
}

