#!/bin/bash

echo "🔍 VÉRIFICATION DU STATUT NETLIFY"
echo "=================================="
echo ""
echo "📋 CHECKLIST:"
echo ""
echo "1. Le dernier commit poussé est: 3331cbb8"
echo "   - Contient netlify.toml"
echo "   - Force la version 1.0.1"
echo ""
echo "2. Sur Netlify, vous devez voir:"
echo "   - Deploy log mentionnant le commit 3331cbb8"
echo "   - Pas d'erreurs de build"
echo ""
echo "3. Après le build, testez:"
echo "   - Ouvrez https://app.clearportx.com"
echo "   - F12 → Console"
echo "   - Cherchez: 'Build version: 1.0.1'"
echo ""
echo "❌ SI VOUS VOYEZ ENCORE LES ANCIENNES ERREURS:"
echo "   → Netlify → Deploys → Trigger deploy → CLEAR CACHE AND DEPLOY"
echo ""
echo "✅ VOTRE BACKEND FONCTIONNE:"
curl -s https://nonexplicable-lacily-leesa.ngrok-free.dev/api/pools | jq '.[0] | {poolId, paire: (.symbolA + "/" + .symbolB)}'
