// Copyright (c) 2025, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: 0BSD

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    
    // Add Digital Asset JFrog Artifactory repositories
    maven {
        name = "DigitalAssetJFrogAssembly"
        url = uri("https://digitalasset.jfrog.io/artifactory/assembly")
        credentials(Credentials.fromNetRc("digitalasset.jfrog.io"))
    }
    
    maven {
        name = "DigitalAssetJFrogMaven"
        url = uri("https://digitalasset.jfrog.io/artifactory/maven")
        credentials(Credentials.fromNetRc("digitalasset.jfrog.io"))
    }
    
    maven {
        name = "DigitalAssetJFrogLibs"
        url = uri("https://digitalasset.jfrog.io/artifactory/libs-release")
        credentials(Credentials.fromNetRc("digitalasset.jfrog.io"))
    }
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.apache.commons:commons-text:1.11.0")
    }

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
