// Copyright (c) 2025, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: 0BSD

/*
 * This source file was generated by the Gradle 'init' task
 */
package com.digitalasset.quickstart;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration;
import org.springframework.boot.context.properties.ConfigurationPropertiesScan;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication(exclude = {SecurityAutoConfiguration.class})
@ConfigurationPropertiesScan("com.digitalasset.quickstart")
@EnableScheduling
public class App {
    private static Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        // CLI short-circuit: run local tools without starting Spring Boot.
        if (args != null && args.length > 0 && "accept-transfer-offer".equals(args[0])) {
            try {
                com.digitalasset.quickstart.tools.AcceptTransferOfferTool.runCli(args);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(2);
            }
            return;
        }
        if (args != null && args.length > 0 && "accept-wallet-transfer-offers".equals(args[0])) {
            try {
                com.digitalasset.quickstart.tools.AcceptWalletTransferOffersTool.runCli(args);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(2);
            }
            return;
        }
        if (args != null && args.length > 0 && "download-package".equals(args[0])) {
            try {
                com.digitalasset.quickstart.tools.DownloadPackageTool.runCli(args);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(2);
            }
            return;
        }
        if (args != null && args.length > 0 && "accept-offer".equals(args[0])) {
            try {
                com.digitalasset.quickstart.tools.AcceptOfferByIdTool.runCli(args);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(2);
            }
            return;
        }
        if (args != null && args.length > 0 && "list-packages".equals(args[0])) {
            try {
                com.digitalasset.quickstart.tools.ListPackagesTool.runCli(args);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(2);
            }
            return;
        }
        if (args != null && args.length > 0 && "inspect-offer".equals(args[0])) {
            try {
                com.digitalasset.quickstart.tools.InspectOfferTool.runCli(args);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(2);
            }
            return;
        }
        if (args != null && args.length > 0 && "inspect-offer-package".equals(args[0])) {
            try {
                com.digitalasset.quickstart.tools.InspectOfferPackageTool.runCli(args);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(2);
            }
            return;
        }

        if (args != null && args.length > 0 && "scan-update".equals(args[0])) {
            try {
                com.digitalasset.quickstart.tools.ScanUpdateTool.runCli(args);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(2);
            }
            return;
        }
        if (args != null && args.length > 0 && "scan-acs".equals(args[0])) {
            try {
                com.digitalasset.quickstart.tools.ScanAcsTool.runCli(args);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(2);
            }
            return;
        }
        if (args != null && args.length > 0 && "find-transfer-instruction".equals(args[0])) {
            try {
                com.digitalasset.quickstart.tools.FindTransferInstructionTool.runCli(args);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(2);
            }
            return;
        }
        if (args != null && args.length > 0 && "accept-cbtc-transfer".equals(args[0])) {
            try {
                com.digitalasset.quickstart.tools.AcceptCbtcTransferTool.runCli(args);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(2);
            }
            return;
        }
        if (args != null && args.length > 0 && "show-transfer-deadline".equals(args[0])) {
            try {
                com.digitalasset.quickstart.tools.ShowTransferDeadlineTool.runCli(args);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(2);
            }
            return;
        }

        if (args != null && args.length > 0 && "decode-offer-blob".equals(args[0])) {
            try {
                com.digitalasset.quickstart.tools.DecodeOfferBlobTool.runCli(args);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(2);
            }
            return;
        }
        if (args != null && args.length > 0 && "dump-offer-create-args".equals(args[0])) {
            try {
                com.digitalasset.quickstart.tools.DumpOfferCreateArgsTool.runCli(args);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(2);
            }
            return;
        }
        if (args != null && args.length > 0 && "exercise-by-interface".equals(args[0])) {
            try {
                com.digitalasset.quickstart.tools.ExerciseByInterfaceTool.runCli(args);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(2);
            }
            return;
        }
        if (args != null && args.length > 0 && "accept-transfer-instruction".equals(args[0])) {
            try {
                com.digitalasset.quickstart.tools.AcceptTransferInstructionTool.runCli(args);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(2);
            }
            return;
        }

        logger.info("Starting application with args: {}", String.join(",", args));
        try {
            SpringApplication.run(App.class, args);
        } catch (Exception e) {
            e.printStackTrace();
            logger.error("Failed to start application" + e.getMessage(), e);
            System.exit(2);
        }
    }
}
